### ISSUE TITLE
Problems when converting to revapi.differences

### ISSUE THREAD

**Issue by vmassol** [revapi/revapi#221]
On XWiki I tried to upgrade to revapi-java 0.22.1 and revapi-maven-plugin 0.12.2 and I've used for example:

```
      <plugin>
        <groupId>org.revapi</groupId>
        <artifactId>revapi-maven-plugin</artifactId>
        <configuration>
          <analysisConfiguration>
            <!-- Add ignores here using the following syntax. You can use a single <revapi.differences> entry but it
                 cannot be empty. You can also use different  <revapi.differences> entries if you wish to use a common
                 justification for example.

                 Note: you can use regexes by using the syntax: <regex>true</regex>
                 Don't forget to '\'-escape dots and other special characters in this case ;)

                 <revapi.differences>
                   <justification>This change is necessary to fix bug #1234</justification>
                   <criticality>hightlight</criticality>
                   <differences>
                     <item>
                       <code>java.method.addToInterface</code>
                       <fullQualifiedClassName>com.acme.ToolInterface</fullyQualifiedClassName>
                       <new>method void com.acme.ToolInterface::setup()</new>
                     </item>
                     <item>
                       <code>java.method.removed</code>
                       <fullQualifiedClassName>com.acme.ToolInterface</fullyQualifiedClassName>
                       <old>method void com.acme.ToolInterface::initialize()</old>
                       <justification>...</justification>
                     </item>
                   </differences>
                 </revapi.differences>
            -->
            <revapi.differences>
              <differences>
                <item>
                  <code>java.method.removed</code>
                  <old>method void org.xwiki.diff.xml.XMLDiff::xxx()</old>
                  <justification>Unstable API added by mistake.</justification>
                </item>
              </differences>
            </revapi.differences>
          </analysisConfiguration>
        </configuration>
      </plugin>
```

When executing it I got:

```
[INFO] --- revapi-maven-plugin:0.12.2:check (revapi-check) @ xwiki-commons-diff-xml ---
[INFO] Comparing [org.xwiki.commons:xwiki-commons-diff-xml:jar:12.10] against [org.xwiki.commons:xwiki-commons-diff-xml:jar:13.0-SNAPSHOT] (including their transitive dependencies).
[WARNING] The `revapi.reclassify` extension is deprecated. Consider using the `revapi.differences` instead.
[WARNING] The `revapi.ignore` extension is deprecated. Consider using the `revapi.differences` instead.
[INFO] API problems found.
[INFO] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore these changes or provide justifications for them, add the xml snippets to your Revapi configuration for the "revapi.differences" extension.

<item>
  <code>java.method.removed</code>
  <old>method void org.xwiki.diff.xml.XMLDiff::xxx()</old>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item><item>
  <code>java.method.removed</code>
  <old>method void org.xwiki.diff.xml.XMLDiff::xxx()</old>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
```

It seems to me that there's a duplicated difference listed, no?

Also I'm not sure why but it seems my `<revapi.differences>` has not been taken into account. Note that we also have https://github.com/xwiki/xwiki-commons/blob/13bcf8d73d2cd6991e3cbcbc85eb4a3ab4673dc8/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/revapi.json configured. Could it be that we cannot mix revapi.ignore with revapi.differences?

Thanks!

**Comment by metlos** [comment]
I just released revapi-maven-plugin-0.13.0 and revapi-java-0.23.0 and I couldn't reproduce this with those versions. That said, I couldn't reproduce it with revapi-maven-plugin-0.12.2 and revapi-java-0.22.1 either. I just tried to build directly the `org.xwiki.commons:xwiki-commons-diff-xml` module with

```
mvn clean verify -Pxwiki -DskipTests -Dxwiki.compatibility.previous.version=12.10
```

Could you please try it again and see if it fixed itself on your side, too? :) If not, we will have to dig deeper into what's the diff between our envs...

**Comment by vmassol** [comment]
@metlos Thanks! I've just tried it again and I get:

```
[WARNING] Extension 'differences' doesn't declare a JSON schema but XML contains its configuration. Cannot convert it into JSON and will ignore it!
[WARNING] Filtering using the revapi.java.filter.(classes|packages) has been deprecated in favor of revapi.filter in combination with the java matcher.
```

Could you help me fix the problems?

Do I need to convert our revapi.json file at https://github.com/xwiki/xwiki-commons/blob/13bcf8d73d2cd6991e3cbcbc85eb4a3ab4673dc8/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/revapi.json and somehow replace the  `"extension": "revapi.ignore",...` part? I guess it's a good thing to do anyway. Some examples on how to convert it would be much appreciated :)

Thanks a lot

**Comment by metlos** [comment]
```
[WARNING] Extension 'differences' doesn't declare a JSON schema but XML contains its configuration. Cannot convert it into JSON and will ignore it!
```
This seems like a misconfiguration actually coming from elsewhere than that json config file...

As for the `revapi.json` you provided, without any testing at all, I'd convert it like this (hoepfully that would be a good starting point for you):

```javascript
[
  {
    "extension": "revapi.filter",
    "configuration": {
      // Note that we currently don't include non-XWiki classes in the checks, the reason being that
      // third-party deps break backward-compat or source compat all the time and we would need to have
      // excludes all the time. So we currently trust them that the breakages are not real breakages
      // that will affect us. We should probably improve this in the future.
      "include": [
        {
          "matcher": "java",
          "match": "type ^org.xwiki.** {}"
        },
        {
          "matcher": "java",
          "match": "type ^com.xpn.xwiki.** {}"
        },
      ],
      "exclude": [
        {
          "matcher": "java",
          "match": "type ^org.wiki.**.internal.** {}"
        },
        {
          "matcher": "java",
          "match": "type ^org.wiki.**.test.** {}"
        },
        {
          "matcher": "java",
          "match": "type ^com.xpn.wiki.**.internal.** {}"
        },
        {
          "matcher": "java",
          "match": "@org.xwiki.stability.Unstable ^*;"
        },
      ]
    }
  },
  {
    "extension": "revapi.differences",
    "configuration": {
      "differences": [
        // these ignores should not actually be needed if we exclude every @Unstable element from the analysis using the rule above
        {
          "regex": true",
          "ignore": true,
          "code": "java.annotation.(added|removed)",
          "annotationType": "org\\.xwiki\\.stability\\.Unstable",
          "justification": "These are marker annotations that have no semantical consequences."
        },
        {
          "regex": true,
          "ignore": true,
          "code": "java.annotation.(added|removed)",
          "annotationType": "java\\.lang\\.SafeVarargs",
          "justification": "Not a breakage. Indicates that the body of the annotated method or constructor does not perform potentially unsafe operations on its varargs parameter. It has no semantic consequences."
        },
        {
          // The "externalClassExposedInAPI" check is used to detect code smells. It's documented as:
          // "This is reported for classes from dependencies that are exposed in the API (for example as a
          // return value). This is generally discouraged practice because it makes updating the dependency
          // version a more complex task (you want a bugfix but you don’t want the changed API to leak to your
          // users)."
          // In the case of XWiki it's not a problem because we release all modules together using the same
          // versioning. However we still want to detect this for non XWiki classes.
          "regex": true,
          "ignore": true,
          "code": "java\\.class\\.externalClassExposedInAPI",
          "package": "org\\.xwiki\\..*",
          "justification": "Dragging of other XWiki types to the API is OK."
        },
        // Same rule for the old com.xpn.xwiki package.
        {
          "regex": true,
          "ignore": true,
          "code": "java\\.class\\.externalClassExposedInAPI",
          "package": "com\\.xpn\\.xwiki\\..*",
          "justification": "Dragging of other XWiki types to the API is OK."
        },
        {
          // We reclassify all source compatibility checks to be of EQUIVALENT severity so that the build doesn't fail on
          // source incompatibilities since we're only interested in binary and (some) semantic incompatibilities. As we
          // break on potentiallyBreaking severity, issues with equivalent severity won't stop the build.
          "regex" : true,
          "code" : ".*",
          "classify" : {
            "SOURCE" : "EQUIVALENT"
          }
        }
      ]
    }
  }
]
```

**Comment by vmassol** [comment]
@metlos  thanks a lot!

I have some questions.

1)

> Quick question about:

```
           "matcher": "java",
          "match": "type ^org.wiki.**.internal.** {}"
```

Will this match for example `org.xwiki.test.internal` ? (ie is the last dot in `"type ^org.wiki.**.internal.** {}"` going to be an issue or not - should I write `"type ^org.wiki.**.internal** {}"` instead?).  I checked https://revapi.org/revapi-java/element-matching.html but couldn't find help on the java matcher syntax.

Also, you've moved the reclassify config under `"extension": "revapi.differences"`(it was under `"extension": "revapi.reclassify",` before), is that normal?

2) I see you've not used a "elements" subcategory in your conversion of `revapi.json`, as indicated on https://revapi.org/revapi-basic-features/filter.html

```
  "extension": "revapi.filter",
    "configuration" : {
      "elements" : {
        "include" 
...
```

vs

```
  "extension": "revapi.filter",
    "configuration" : {
        "include" 
```

Is that normal?

 3) I'm not sure how to diagnostic "[WARNING] Extension 'differences' doesn't declare a JSON schema but XML contains its configuration. Cannot convert it into JSON and will ignore it!" Any idea? I did a `mvn help:effective-pom` but couldn't see anything special.

Thanks

**Comment by metlos** [comment]
The matching is done using the classif library that is documented externally:  https://github.com/revapi/classif

**Comment by metlos** [comment]
To answer your first question... `type ^org.wiki.**.internal.** {}` means to match any type which has the fqn matching the glob pattern `org.xwiki.**.internal.**`. The fqn is understood to just be a dot-separated list of names. `**` means "0 or more elements", the same as it is understood in Ant file matching expressions for example. So since we're matching types, the fqn on that type needs to start with `org.xwiki` followed by 0 or more futher dot-separated names, then there needs to be a name `internal` and after that 0 or more further elements (the last of which is going to be the class name itself).

**Comment by metlos** [comment]
> Also, you've moved the reclassify config under "extension": "revapi.differences"(it was under "extension": "revapi.reclassify", before), is that normal?

Yes, `revapi.differences` can stand for both `revapi.ignore` and `revapi.reclassify`. The idea is that you just list all the differences in one place and at each difference you're able to tell revapi what to do with it - ignore, reclassify, change its attachments or criticality, ...

**Comment by metlos** [comment]
To answer your question number 2, no - that was my mistake and your sharp eyes in action :) The "elements" should be there as you noticed...

**Comment by metlos** [comment]
> 
>  3.  I'm not sure how to diagnostic "[WARNING] Extension 'differences' doesn't declare a JSON schema but XML contains its configuration. Cannot convert it into JSON and will ignore it!" Any idea? I did a mvn help:effective-pom but couldn't see anything special.

when you run the build with `-X`, revapi should dump its full configuration merged from the various configuratio locations. Maybe we will learn something from that?

**Comment by vmassol** [comment]
After adding the "elements" level, I now get:

```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.11.5:check (revapi-check) on project xwiki-platform-extension-script: Failed to execute the API analysis.: Failed to analyze archives: Illegal repetition
[ERROR] {"matcher" => "java","match" => "type ^org.xwiki.** {}"}
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.revapi:revapi-maven-plugin:0.11.5:check (revapi-check) on project xwiki-platform-extension-script: Failed to execute the API analysis.
...
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to execute the API analysis.
...
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to analyze archives
    at org.revapi.maven.Analyzer.analyze (Analyzer.java:424)
    at org.revapi.maven.AbstractRevapiMojo.analyze (AbstractRevapiMojo.java:297)
    at org.revapi.maven.CheckMojo.execute (CheckMojo.java:82)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
...
```

I have:

```
[
  {
    "extension": "revapi.filter",
    "configuration": {
      "elements" : {
        // Note that we currently don't include non-XWiki classes in the checks, the reason being that
        // third-party deps break backward-compat or source compat all the time and we would need to have
        // excludes all the time. So we currently trust them that the breakages are not real breakages
        // that will affect us. We should probably improve this in the future.
        "include": [
          {
            "matcher": "java",
            "match": "type ^org.xwiki.** {}"
          },
          {
            "matcher": "java",
            "match": "type ^com.xpn.xwiki.** {}"
          }
        ],
        "exclude": [
          {
            "matcher": "java",
            "match": "type ^org.wiki.**.internal.** {}"
          },
          {
            "matcher": "java",
            "match": "type ^org.wiki.**.test.** {}"
          },
          {
            "matcher": "java",
            "match": "type ^com.xpn.wiki.**.internal.** {}"
          },
          {
            "matcher": "java",
            "match": "@org.xwiki.stability.Unstable ^*;"
          }
        ]
      }
    }
  },
...
```

Can you see anything wrong?

Thanks

**Comment by vmassol** [comment]
Note: works much better with 0.13.2 and 0.23.2 (instead of 0.13.0 and 0.23.0) :)

I still have some warnings and a logger ERROR:

```
[INFO] --- revapi-maven-plugin:0.13.2:check (revapi-check) @ xwiki-platform-extension-script ---
[INFO] Comparing [org.xwiki.platform:xwiki-platform-extension-script:jar:12.10.2] against [org.xwiki.platform:xwiki-platform-extension-script:jar:13.0-SNAPSHOT] (including their transitive dependencies).
[WARNING] Extension 'differences' doesn't declare a JSON schema but XML contains its configuration. Cannot convert it into JSON and will ignore it!
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
[WARNING] The `revapi.reclassify` extension is deprecated. Consider using the `revapi.differences` instead.
[INFO] API checks completed without failures.
```

**Comment by metlos** [comment]
Good :)

```
[WARNING] Extension 'differences' doesn't declare a JSON schema but XML contains its configuration. Cannot convert it into JSON and will ignore it!
```
This is bothering me - not sure where this can be coming from...

```
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
```
Hmm... let's see what i can do about this...

```
[WARNING] The `revapi.reclassify` extension is deprecated. Consider using the `revapi.differences` instead.
```
Fix already in master. The dreaded boolean logic! :)

**Comment by vmassol** [comment]
> This is bothering me - not sure where this can be coming from...

My guess, without knowing it more is that the revapi.json file is JSON and for some reason revapi is considering that the XML declaration should be json and is trying to convert it to json. I'm probably wrong though ;)

Thanks

**Comment by vmassol** [comment]
@metlos hi! Have you been able to check more about why we the problem on xwiki when we upgraded, see https://groups.google.com/g/revapi/c/wLopI7LLeEc  Thanks :)

**Comment by metlos** [comment]
This is fixed in the main branch. I'm currently finishing up the new set of releases which should hopefully happen in the coming days (if everything goes well, I might get it ready this week, but it could take more time than that)...

**Comment by metlos** [comment]
At last, new stuff is out: https://revapi.org/revapi-site/main/downloads.html

Can you try with the newest versions, pls?

**Comment by vmassol** [comment]
> Can you try with the newest versions, pls?

yipee! :)

Just tried on the XCOMMONS-1995 branch in commons and I get the following warnings (for example).

```
[INFO] --- revapi-maven-plugin:0.14.0:check (default-cli) @ xwiki-commons-core ---
[INFO] Comparing [org.xwiki.commons:xwiki-commons-core:pom:13.1] against [org.xwiki.commons:xwiki-commons-core:pom:13.2-SNAPSHOT] (including their transitive dependencies).
[WARNING] Filtering using the revapi.java.filter.(classes|packages) has been deprecated in favor of revapi.filter in combination with the java matcher.
[WARNING] The `revapi.ignore` extension is deprecated. Consider using the `revapi.differences` instead.
[WARNING] The `revapi.reclassify` extension is deprecated. Consider using the `revapi.differences` instead.
[INFO] API checks completed without failures.
```

I don't see any usage of `revapi.java.filter`, `revapi.ignore` or `revapi.reclassify` though.:
* `revapi.json` uses `revapi.filter`, see https://github.com/xwiki/xwiki-commons/blob/XCOMMONS-1995/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/revapi.json
* the `pom.xml` uses `revapi.differences`, see https://github.com/xwiki/xwiki-commons/blob/XCOMMONS-1995/xwiki-commons-core/pom.xml#L198-L211

Any idea?

Thanks

**Comment by metlos** [comment]
When you run the maven build with `-X` revapi should output the effective configuration it gathered from all sources. Look for `[DEBUG] Effective analysis configuration:` What does it say?

**Comment by vmassol** [comment]
Side note: I'm not even sure why revapi executes for a `pom` packaging project? :)

**Comment by vmassol** [comment]
> What does it say?

```
[INFO] Comparing [org.xwiki.commons:xwiki-commons-core:pom:13.1] against [org.xwiki.commons:xwiki-commons-core:pom:13.2-SNAPSHOT] (including their transitive dependencies).
[DEBUG] Effective analysis configuration:
[
    {
        "extension" : "revapi.java",
        "configuration" : {"filter" : {"packages" : {
            "regex" : true,
            "include" : [
                "org\\.xwiki\\..*",
                "com\\.xpn\\.xwiki\\..*"
            ],
            "exclude" : [
                "org\\.xwiki\\..*\\.internal(\\..*)?",
                "org\\.xwiki\\..*\\.test(\\..*)?",
                "com\\.xpn\\.xwiki\\.internal(\\..*)?"
            ]
        }}}
    },
    {
        "extension" : "revapi.ignore",
        "configuration" : [
            {
                "code" : "java.annotation.removed",
                "annotationType" : "org.xwiki.stability.Unstable",
                "justification" : "These are marker annotations that have no semantical consequences."
            },
            {
                "code" : "java.annotation.added",
                "annotationType" : "org.xwiki.stability.Unstable",
                "justification" : "Not a breakage. Indicates API readiness only and has no semantic consequences."
            },
            {
                "code" : "java.annotation.added",
                "annotationType" : "java.lang.SafeVarargs",
                "justification" : "Not a breakage. Indicates that the body of the annotated method or constructor does not perform potentially unsafe operations on its varargs parameter. It has no semantic consequences."
            },
            {
                "regex" : true,
                "code" : "java\\.class\\.externalClassExposedInAPI",
                "package" : "org\\.xwiki\\..*",
                "justification" : "Dragging of other XWiki types to the API is OK."
            },
            {
                "regex" : true,
                "code" : "java\\.class\\.externalClassExposedInAPI",
                "package" : "com\\.xpn\\.xwiki\\..*",
                "justification" : "Dragging of other XWiki types to the API is OK."
            }
        ]
    },
    {
        "extension" : "revapi.reclassify",
        "configuration" : [{
            "regex" : true,
            "code" : ".*",
            "classify" : {"SOURCE" : "EQUIVALENT"}
        }]
    },
    {
        "extension" : "revapi.differences",
        "configuration" : {
            "justification" : "Not a breakage for scripts",
            "criticality" : "highlight",
            "differences" : [
                {
                    "code" : "java.method.removed",
                    "old" : "method java.lang.String org.apache.velocity.tools.generic.ComparisonDateTool::toString(long, int, int, boolean, java.util.Locale) @ org.xwiki.velocity.tools.ComparisonDateTool"
                },
                {
                    "code" : "java.method.removed",
                    "old" : "method java.lang.String org.apache.velocity.tools.generic.ComparisonDateTool::toString(long, int, boolean, java.util.Locale) @ org.xwiki.velocity.tools.ComparisonDateTool"
                }
            ]
        }
    }
]
[DEBUG] Analysis starts
```

However, as I mentioned above this doesn't seem to come from the current sources on which I execute the build. Could it be coming from the sources of the previous version revapi compares with? In this case with 13.1: https://github.com/xwiki/xwiki-commons/blob/xwiki-commons-13.1/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/revapi.json ?

Thanks

**Comment by metlos** [comment]
> Side note: I'm not even sure why revapi executes for a pom packaging project? :)
yeah - it eventually gives up and doesn't do the analysis, but it initializes itself before that.. This should be improved :)

**Comment by vmassol** [comment]
Note that XCOMMONS-1995 branch still has the breaking change from https://github.com/xwiki/xwiki-commons/compare/XCOMMONS-1995#diff-a949f7749eef7e5d42da3a96cafc2a0a8022638a44ac447fae1ad477940b7f78R50-R54 

However revapi still doesn't break on it (and there's no ignore for that), so it seems the issue is still there.

Sorry ... :)

**Comment by metlos** [comment]
Note to self - running with debug logs gives:
```
[DEBUG] Difference transform class org.revapi.basic.DifferencesTransform transforms Difference[code='java.method.addedToInterface', name='method added to interface', classification={BINARY=NON_BREAKING, SOURCE=EQUIVALENT, SEMANTIC=POTENTIALLY_BREAKING}, description='Method was added to an interface.', justification='Not a breakage for scripts', criticality='Criticality[name='highlight', level=3000]'] to [Difference[code='java.method.addedToInterface', name='method added to interface', classification={BINARY=NON_BREAKING, SOURCE=EQUIVALENT, SEMANTIC=POTENTIALLY_BREAKING}, description='Method was added to an interface.', justification='Not a breakage for scripts', criticality='Criticality[name='highlight', level=3000]']]
```

so it seems the difference is detected but the build doesn't fail on it even though it should given:
```
[DEBUG] Configuring mojo 'org.revapi:revapi-maven-plugin:0.14.0:check' with basic configurator -->
[DEBUG]   (f) alwaysCheckForReleaseVersion = true
[DEBUG]   (f) analysisConfiguration = <analysisConfiguration><revapi.differences><justification>Not a breakage for scripts</justification>
<criticality>highlight</criticality>
<differences><item><code>java.method.removed</code>
<old>method java.lang.String org.apache.velocity.tools.generic.ComparisonDateTool::toString(long, int, int, boolean, java.util.Locale) @ org.xwiki.velocity.tools.ComparisonDateTool</old>
</item>
<item><code>java.method.removed</code>
<old>method java.lang.String org.apache.velocity.tools.generic.ComparisonDateTool::toString(long, int, boolean, java.util.Locale) @ org.xwiki.velocity.tools.ComparisonDateTool</old>
</item>
</differences>
</revapi.differences>
</analysisConfiguration>

[DEBUG]   (s) resource = revapi.json
[DEBUG]   (f) analysisConfigurationFiles = [org.revapi.maven.ConfigurationFile@4bb747c1]
[DEBUG]   (f) checkDependencies = true
[DEBUG]   (f) expandProperties = false
[DEBUG]   (f) failBuildOnProblemsFound = true
[DEBUG]   (f) failOnMissingConfigurationFiles = true
[DEBUG]   (f) failOnUnresolvedArtifacts = false
[DEBUG]   (f) failOnUnresolvedDependencies = false
[DEBUG]   (f) failSeverity = potentiallyBreaking
[DEBUG]   (f) ignoreSuggestionsFormat = xml
[DEBUG]   (f) newArtifacts = []
[DEBUG]   (f) newVersion = 13.2-SNAPSHOT
[DEBUG]   (f) oldArtifacts = []
[DEBUG]   (f) oldVersion = 13.1
[DEBUG]   (f) outputIgnoreSuggestions = true
[DEBUG]   (f) outputNonIdentifyingDifferenceInfo = false
[DEBUG]   (f) project = MavenProject: org.xwiki.commons:xwiki-commons-blame-api:13.2-SNAPSHOT @ /home/brq/lkrejci/Projects/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/pom.xml
[DEBUG]   (f) repositorySystemSession = org.eclipse.aether.DefaultRepositorySystemSession@3ef8de39
[DEBUG]   (f) resolveProvidedDependencies = true
[DEBUG]   (f) resolveTransitiveProvidedDependencies = false
[DEBUG]   (f) skip = false
```

**Comment by metlos** [comment]
@vmassol so let's try with `revapi-maven-plugin:0.14.1` and `revapi-java:0.24.1` that I just released. The difference should now be reported - not sure about the warnings - but I consider that a lower priority.

**Comment by vmassol** [comment]
@metlos I think there might have been a problem in your bug fix release since I get:

```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.14.1:check (default-cli) on project xwiki-commons: Execution default-cli of goal org.revapi:revapi-maven-plugin:0.14.1:check failed: Plugin org.revapi:revapi-maven-plugin:0.14.1 or one of its dependencies could not be resolved: Failure to find org.revapi:revapi-maven-utils:jar:0.10.5-SNAPSHOT in http://nexus.xwiki.org/nexus/content/groups/public-snapshots was cached in the local repository, resolution will not be reattempted until the update interval of xwiki-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
```

The fact that `0.10.5-SNAPSHOT` is mentioned seems like a release bug.

**Comment by vmassol** [comment]
> yeah - it eventually gives up and doesn't do the analysis, but it initializes itself before that.. This should be improved :)

About this, it actually does a lot before it gives up. There are several seconds (not ms but seconds) taken when the following executes:

```
[INFO] --- revapi-maven-plugin:0.11.5:check (revapi-check) @ xwiki-platform-minimaldependencies ---
Downloading from central: https://repo.maven.apache.org/maven2/io/sf/jclf/jclf/maven-metadata.xml
Downloading from xwiki-releases: http://nexus.xwiki.org/nexus/content/groups/public/io/sf/jclf/jclf/maven-metadata.xml
Downloading from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/io/sf/jclf/jclf/maven-metadata.xml
Downloaded from xwiki-releases: http://nexus.xwiki.org/nexus/content/groups/public/io/sf/jclf/jclf/maven-metadata.xml (414 B at 1.9 kB/s)
[INFO] Comparing [org.xwiki.platform:xwiki-platform-minimaldependencies:pom:13.3] against [org.xwiki.platform:xwiki-platform-minimaldependencies:pom:13.4-SNAPSHOT] (including their transitive dependencies).
[INFO] API checks completed without failures.
```

There's the download part first and then the "comparing" is taking several seconds too.

**Comment by metlos** [comment]
revapi-maven-plugin 0.14.2 is out, this time I tried it with clean local repo :) I will take a look at the pom packaging...

**Comment by vmassol** [comment]
@metlos  Thanks. However it's still not finding the breakage... :(

```
vmassol ~/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api (XCOMMONS-1995 *) $ mvn clean revapi:check -Plegacy
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=196m; support was removed in 8.0
[WARNING] Failed to read extensions descriptor /Users/vmassol/dev/xwiki/xwiki-commons/.mvn/extensions.xml: no more data available START_DOCUMENT seen ...</extension>\n</extensions-->... @7:16
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< org.xwiki.commons:xwiki-commons-blame-api >--------------
[INFO] Building XWiki Commons - Blame - API 13.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- revapi-maven-plugin:0.14.2:check (default-cli) @ xwiki-commons-blame-api ---
Downloading from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/org/xwiki/commons/xwiki-commons-blame-api/13.2-SNAPSHOT/maven-metadata.xml
[INFO] Comparing [org.xwiki.commons:xwiki-commons-blame-api:jar:13.1] against [org.xwiki.commons:xwiki-commons-blame-api:jar:13.2-SNAPSHOT] (including their transitive dependencies).
[WARNING] Filtering using the revapi.java.filter.(classes|packages) has been deprecated in favor of revapi.filter in combination with the java matcher.
[WARNING] The `revapi.reclassify` extension is deprecated. Consider using the `revapi.differences` instead.
[WARNING] The `revapi.ignore` extension is deprecated. Consider using the `revapi.differences` instead.
[INFO] API checks completed without failures.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.879 s
[INFO] Finished at: 2021-04-30T19:08:59+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by metlos** [comment]
It does for me.. 😕 

```
$ git log -1 --oneline && mvn revapi:check -Pxwiki
3d396c787 (HEAD -> XCOMMONS-1995, origin/XCOMMONS-1995) XCOMMONS-1995: Upgrade to Revapi  0.24.1 and Maven Revapi 0.14.2
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< org.xwiki.commons:xwiki-commons-blame-api >--------------
[INFO] Building XWiki Commons - Blame - API 13.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- revapi-maven-plugin:0.14.2:check (default-cli) @ xwiki-commons-blame-api ---
Downloading from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/org/xwiki/commons/xwiki-commons-blame-api/13.2-SNAPSHOT/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/xwiki/commons/xwiki-commons-blame-api/13.2-SNAPSHOT/maven-metadata.xml
[INFO] Comparing [org.xwiki.commons:xwiki-commons-blame-api:jar:13.1] against [org.xwiki.commons:xwiki-commons-blame-api:jar:13.2-SNAPSHOT] (including their transitive dependencies).
[INFO] API problems found.
[INFO] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore these changes or provide justifications for them, add the xml snippets to your Revapi configuration for the "revapi.differences" extension.

<item>
  <ignore>true</ignore>
  <code>java.method.addedToInterface</code>
  <new>method void org.xwiki.blame.AnnotatedContent&lt;R, E&gt;::xxx()</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.938 s
[INFO] Finished at: 2021-05-01T11:55:21+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.14.2:check (default-cli) on project xwiki-commons-blame-api: The following API problems caused the build to fail:
[ERROR] java.method.addedToInterface: method void org.xwiki.blame.AnnotatedContent<R, E>::xxx(): Method was added to an interface.
[ERROR] 
[ERROR] Consult the plugin output above for suggestions on how to ignore the found problems.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by vmassol** [comment]
@metlos quite weird. Just ran it again:

```
vmassol ~/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api (XCOMMONS-1995) $ git log -1 --oneline && mvn revapi:check -Pxwiki
3d396c787 (HEAD -> XCOMMONS-1995, origin/XCOMMONS-1995) XCOMMONS-1995: Upgrade to Revapi  0.24.1 and Maven Revapi 0.14.2
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=196m; support was removed in 8.0
[WARNING] Failed to read extensions descriptor /Users/vmassol/dev/xwiki/xwiki-commons/.mvn/extensions.xml: no more data available START_DOCUMENT seen ...</extension>\n</extensions-->... @7:16
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< org.xwiki.commons:xwiki-commons-blame-api >--------------
[INFO] Building XWiki Commons - Blame - API 13.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- revapi-maven-plugin:0.14.2:check (default-cli) @ xwiki-commons-blame-api ---
Downloading from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/org/xwiki/commons/xwiki-commons-blame-api/13.2-SNAPSHOT/maven-metadata.xml
[INFO] Comparing [org.xwiki.commons:xwiki-commons-blame-api:jar:13.1] against [org.xwiki.commons:xwiki-commons-blame-api:jar:13.2-SNAPSHOT] (including their transitive dependencies).
[WARNING] Filtering using the revapi.java.filter.(classes|packages) has been deprecated in favor of revapi.filter in combination with the java matcher.
[WARNING] The `revapi.ignore` extension is deprecated. Consider using the `revapi.differences` instead.
[WARNING] The `revapi.reclassify` extension is deprecated. Consider using the `revapi.differences` instead.
[INFO] API checks completed without failures.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.200 s
[INFO] Finished at: 2021-05-01T14:41:28+02:00
[INFO] ------------------------------------------------------------------------
vmassol ~/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api (XCOMMONS-1995) $ 
```

**Comment by vmassol** [comment]
So let's see what could be different: Maven or the Java version.

```
vmassol ~/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api (XCOMMONS-1995) $ mvn -v
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=196m; support was removed in 8.0
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Applications/apache-maven-3.6.3
Java version: 1.8.0_202, vendor: AdoptOpenJdk, runtime: /Library/Java/JavaVirtualMachines/jdk8u202-b08/Contents/Home/jre
Default locale: en_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

**Comment by metlos** [comment]
So just to be sure I deleted everything from the local maven cache and switched back to java 8. Still I get the error: https://gist.github.com/metlos/a4088cace807734b92fc6f4b20759863

**Comment by metlos** [comment]
Interestingly I also don't get the warnings:
```
[WARNING] Filtering using the revapi.java.filter.(classes|packages) has been deprecated in favor of revapi.filter in combination with the java matcher.
[WARNING] The `revapi.ignore` extension is deprecated. Consider using the `revapi.differences` instead.
[WARNING] The `revapi.reclassify` extension is deprecated. Consider using the `revapi.differences` instead.
```
is present in your output, but not in mine.

**Comment by vmassol** [comment]
@metlos so I was able to reproduce your result by pointing maven to a new local repo. Cool. I'll now continue my testing and push that to master thanks!

**Comment by vmassol** [comment]
@metlos just found that it now fails on platform with:

```
[INFO] ---------< org.xwiki.platform:xwiki-platform-extension-script >---------
[INFO] Building XWiki Platform - Extension - Script 13.4-SNAPSHOT     [121/465]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- revapi-maven-plugin:0.14.2:check (default-cli) @ xwiki-platform-extension-script ---
Downloading from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/io/sf/jclf/jclf/maven-metadata.xml
Downloading from xwiki-releases: http://nexus.xwiki.org/nexus/content/groups/public/io/sf/jclf/jclf/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/io/sf/jclf/jclf/maven-metadata.xml
Downloaded from xwiki-releases: http://nexus.xwiki.org/nexus/content/groups/public/io/sf/jclf/jclf/maven-metadata.xml (414 B at 5.4 kB/s)
Downloading from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/org/xwiki/platform/xwiki-platform-extension-script/13.4-SNAPSHOT/maven-metadata.xml
Downloaded from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/org/xwiki/platform/xwiki-platform-extension-script/13.4-SNAPSHOT/maven-metadata.xml (799 B at 16 kB/s)
Downloading from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/org/xwiki/platform/xwiki-platform-oldcore/13.4-SNAPSHOT/maven-metadata.xml
Downloaded from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/org/xwiki/platform/xwiki-platform-oldcore/13.4-SNAPSHOT/maven-metadata.xml (1.0 kB at 17 kB/s)
Downloading from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/org/xwiki/platform/xwiki-platform-office-importer/13.4-SNAPSHOT/maven-metadata.xml
Downloaded from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/org/xwiki/platform/xwiki-platform-office-importer/13.4-SNAPSHOT/maven-metadata.xml (798 B at 13 kB/s)
Downloading from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/org/xwiki/platform/xwiki-platform-refactoring-api/13.4-SNAPSHOT/maven-metadata.xml
Downloaded from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/org/xwiki/platform/xwiki-platform-refactoring-api/13.4-SNAPSHOT/maven-metadata.xml (798 B at 14 kB/s)
Downloading from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/org/xwiki/platform/xwiki-platform-security-authentication-api/13.4-SNAPSHOT/maven-metadata.xml
Downloaded from xwiki-snapshots: http://nexus.xwiki.org/nexus/content/groups/public-snapshots/org/xwiki/platform/xwiki-platform-security-authentication-api/13.4-SNAPSHOT/maven-metadata.xml (810 B at 14 kB/s)
[INFO] Comparing [org.xwiki.platform:xwiki-platform-extension-script:jar:13.3] against [org.xwiki.platform:xwiki-platform-extension-script:jar:13.4-SNAPSHOT] (including their transitive dependencies).
[WARNING] The `revapi.ignore` extension is deprecated. Consider using the `revapi.differences` instead.
[INFO] API problems found.
[INFO] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore these changes or provide justifications for them, add the xml snippets to your Revapi configuration for the "revapi.differences" extension.

<item>
  <ignore>true</ignore>
  <code>java.missing.oldClass</code>
  <old>missing-class javax.servlet.http.Cookie</old>
  <new>missing-class javax.servlet.http.Cookie</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <ignore>true</ignore>
  <code>java.missing.newClass</code>
  <old>missing-class javax.servlet.http.Cookie</old>
  <new>missing-class javax.servlet.http.Cookie</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <ignore>true</ignore>
  <code>java.missing.oldClass</code>
  <old>missing-class javax.servlet.http.HttpServletRequest</old>
  <new>missing-class javax.servlet.http.HttpServletRequest</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <ignore>true</ignore>
  <code>java.missing.newClass</code>
  <old>missing-class javax.servlet.http.HttpServletRequest</old>
  <new>missing-class javax.servlet.http.HttpServletRequest</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <ignore>true</ignore>
  <code>java.missing.oldClass</code>
  <old>missing-class javax.servlet.http.HttpServletResponse</old>
  <new>missing-class javax.servlet.http.HttpServletResponse</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <ignore>true</ignore>
  <code>java.missing.newClass</code>
  <old>missing-class javax.servlet.http.HttpServletResponse</old>
  <new>missing-class javax.servlet.http.HttpServletResponse</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <ignore>true</ignore>
  <code>java.method.removed</code>
  <old>method java.util.List&lt;java.lang.String&gt; com.xpn.xwiki.XWiki::getConfiguredSyntaxes()</old>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
...

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:51 min
[INFO] Finished at: 2021-05-04T19:13:30+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.14.2:check (default-cli) on project xwiki-platform-extension-script: The following API problems caused the build to fail:
[ERROR] java.missing.oldClass: missing-class javax.servlet.http.Cookie: Class 'javax.servlet.http.Cookie' could not be found in the archives of the old API. It has been detected as contributing to the API and thus the analysis results may be incorrect.
[ERROR] java.missing.newClass: missing-class javax.servlet.http.Cookie: Class 'javax.servlet.http.Cookie' could not be found in the archives of the new API. It has been detected as contributing to the API and thus the analysis results may be incorrect.
[ERROR] java.missing.oldClass: missing-class javax.servlet.http.HttpServletRequest: Class 'javax.servlet.http.HttpServletRequest' could not be found in the archives of the old API. It has been detected as contributing to the API and thus the analysis results may be incorrect.
[ERROR] java.missing.newClass: missing-class javax.servlet.http.HttpServletRequest: Class 'javax.servlet.http.HttpServletRequest' could not be found in the archives of the new API. It has been detected as contributing to the API and thus the analysis results may be incorrect.
[ERROR] java.missing.oldClass: missing-class javax.servlet.http.HttpServletResponse: Class 'javax.servlet.http.HttpServletResponse' could not be found in the archives of the old API. It has been detected as contributing to the API and thus the analysis results may be incorrect.
[ERROR] java.missing.newClass: missing-class javax.servlet.http.HttpServletResponse: Class 'javax.servlet.http.HttpServletResponse' could not be found in the archives of the new API. It has been detected as contributing to the API and thus the analysis results may be incorrect.
[ERROR] java.method.removed: method java.util.List<java.lang.String> com.xpn.xwiki.XWiki::getConfiguredSyntaxes(): Method was removed. [org.xwiki.platform:xwiki-platform-oldcore:jar:13.3]
[ERROR] 
[ERROR] Consult the plugin output above for suggestions on how to ignore the found problems.
```

Would you have any idea why we get these that we didn't get with the old version of the revapi plugin?

Thanks

**Comment by vmassol** [comment]
@metlos I'm trying to figure out what `Class 'javax.servlet.http.Cookie' could not be found in the archives of the old API. It has been detected as contributing to the API and thus the analysis results may be incorrect.`  could mean precisely and how to find the part of the code concerned.

There were no source changes in `xwiki-platform-extension-script` between 13.3 and 13.4-SNAPSHOT so it has to come from its dependencies. But how do track down which class is concerned?

I'd like to verify if this is correct or if it's a false positive or bug of revapi.

Thanks

**Comment by vmassol** [comment]
> revapi-maven-plugin 0.14.2 is out, this time I tried it with clean local repo :) I will take a look at the pom packaging...

I've opened https://github.com/revapi/revapi/issues/233

Thanks!

**Comment by metlos** [comment]
> @metlos I'm trying to figure out what Class 'javax.servlet.http.Cookie' could not be found in the archives of the old API. It has been detected as contributing to the API and thus the analysis results may be incorrect. could mean precisely and how to find the part of the code concerned.

Not sure whether this is a change in Revapi config in XWiki or a more strict behavior in Revapi itself since the last upgrade in XWiki, but because the classes from the servlet API are specified as a `provided` dependency of `xwiki-platform-oldcore` and Revapi's `resolveTransitiveProvidedDependencies` defaults to `false` and you don't override it in Xwiki's configuration, Revapi just doesn't find the classes from servlet api but finds them transitively exposed in the API of `xwiki-platform-extension-script` and therefore reports them. So the solution is either to set `resolveTransitiveProvidedDependencies` to `true` in Revapi's config or to declare the servlet API as a compile dependency in `xwiki-platform-oldcore`.

Note that Revapi doesn't include the provided transitive deps by default because that is the same behavior as Maven - if you tried to use a class from servlet API in `xwiki-platform-extension-script`, you'd get a compile error and you'd have to add an explicit dependency on it (either in `xwiki-platform-extension-script` as compile or provided or in `xwiki-platform-oldcore` as compile).

**Comment by vmassol** [comment]
> So the solution is either to set resolveTransitiveProvidedDependencies to true in Revapi's config or to declare the servlet API as a compile dependency in xwiki-platform-oldcore.

Using `provided` is the correct way since the Servlet API is provided in the target environment (the Servlet Container) and should never be included in the WAR.

It seems that setting `resolveTransitiveProvidedDependencies` to true could lead to new problems so I'm not sure that's the right thing to do...

PS: sorry for the delay in answer, I was on holiday for 10 days.

**Comment by metlos** [comment]
I was trying to show how Maven (and Revapi) composes the classpath with provided and compile deps. Only the direct provided dependencies are on the classpath of a module, as opposed to all the transitive compile deps.

I agree with you that `provided` is the right scope for the servlet API, but because you, in a sense, re-export parts of the servlet API in `xwiki-platform-extension-script`, you have to put the servlet API on the classpath somehow (or agree to the fact that Revapi cannot find those classes on the classpath).

What this situation highlights is the fact that if a user of `xwiki-platform-extension-script` followed the call chain leading to the methods from `xwiki-platform-oldcore` that expose the servlet API, they wouldn't be able to use those methods without also **explicitly** including the servlet API on their classpath (basically the user in this case is in the same situation as Revapi when looking at the classpath).

Nevertheless, in your case all of this doesn't really matter 😃  In your setup, you are filtering out all classes outside of `org.xwiki` so the classes never should have bubbled up to the analysis.

**Comment by vmassol** [comment]
> What this situation highlights is the fact that if a user of xwiki-platform-extension-script followed the call chain leading to the methods from xwiki-platform-oldcore that expose the servlet API, they wouldn't be able to use those methods without also explicitly including the servlet API on their classpath (basically the user in this case is in the same situation as Revapi when looking at the classpath).

Yes. It's because Maven doesn't inherit the `provided` scope (it's not transitive). This is also why BTW that we have https://github.com/xwiki/xwiki-platform/blob/22b6dff37fb044dbe113c1d5d0287d8e790d8afa/xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-script/pom.xml#L81-L85 for our tests. So yes any runtime user of `xwiki-platform-extension-script` needs to have the servlet api in the classpath. So this explains why revapi cannot find the `Cookie` class (if it behaves like Maven). However it seems that this was changed recently since that wasn't a problem before, in older versions of revapi.

> Nevertheless, in your case all of this doesn't really matter 😃 In your setup, you are filtering out all classes outside of org.xwiki so the classes never should have bubbled up to the analysis.

So I guess this is a bug in revapi, right? :)

Thanks for the explanations!

**Comment by metlos** [comment]
`revapi-maven-plugin-0.14.3` and `revapi-java-0.24.2` should improve on the missing classes handling. I am no longer going to say that it fixes it, because xwiki is such a great testbed that you always discover all corner cases possible :)

**Comment by vmassol** [comment]
@metlos thanks! I've upgraded and it seems to work. We'll see fully when the CI has finished executing, in a few hours :)

**Comment by metlos** [comment]
Since a few hours have more than passed I'm closing this. Please create new issues for any new problems found.

**Comment by vmassol** [comment]
Thanks @metlos and sorry for not coming back to you. It's working so far :)
