### ISSUE TITLE
Some Java classes are checked even if though the package filter is specified

### ISSUE THREAD

**Issue by MarianMacik** [revapi/revapi#52]
Hi,

I am getting these changes in some of my projects:
{
        "code": "java.missing.newClass",
        "new": "missing-class com.google.errorprone.annotations.CanIgnoreReturnValue",
        "justification": "ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE"
      },
      {
        "code": "java.missing.oldClass",
        "old": "missing-class sun.util.locale.provider.LocaleServiceProviderPool.LocalizedObjectGetter",
        "new": "missing-class sun.util.locale.provider.LocaleServiceProviderPool.LocalizedObjectGetter",
        "justification": "Probably a bug in revapi, nothing serious"
      },
      {
        "code": "java.missing.newClass",
        "old": "missing-class sun.util.locale.provider.LocaleServiceProviderPool.LocalizedObjectGetter",
        "new": "missing-class sun.util.locale.provider.LocaleServiceProviderPool.LocalizedObjectGetter",
        "justification": "Probably a bug in revapi, nothing serious"
      }

It is strange, because I do not have these packages specified in my filter. The config can be found here:
https://github.com/MarianMacik/optaplanner/blob/revapi/optaplanner-core/src/build/revapi-config.json#L1158

The error details are: java.missing.oldClass: missing-class sun.util.locale.provider.LocaleServiceProviderPool.LocalizedObjectGetter: Class 'sun.util.locale.provider.LocaleServiceProviderPool.LocalizedObjectGetter' could not be found in the archives of the old API. It has been detected as contributing to the API and thus the analysis results may be incorrect.
[ERROR] Use chain of the type in the old API:
[ERROR] Use chain of the type in the new API:

Chains are empty even after I turn on "reportUsesFor": ["java.missing.newClass", "java.missing.oldClass"], but this is already documented in #46.

Thanks,

Marian

**Comment by metlos** [comment]
Could you provide more precise repro steps for this please? I've tried checking out your branch and update the revapi config to read the `src/build/revapi-config.json` and commented out the above differences from the ignores. I've tried with revapi-maven-plugin `0.6.1`, `0.7.0` and `0.8.0-SNAPSHOT` with revapi-java `0.10.2`, `0.11.2` and `0.12.0-SNAPSHOT`.

revapi-java `0.10.2` seems to find quite a number of false positives, `0.11.2` finds no differences and so does `0.12.0-SNAPSHOT`. But even `0.10.2` in my configuration doesn't find the above mentioned missing classes.

**Comment by metlos** [comment]
I think this should be fixed by fa9ddf9.

**Comment by MarianMacik** [comment]
Sorry for the confusion. Revapi has not been configured, it is now configured in our parent, but anyway her is the configuration. https://github.com/MarianMacik/optaplanner/blob/revapi-bug/optaplanner-core/pom.xml Please checkout revapi-bug branch and simply run mvn clean install -DskipTests inside optaplanner-core module. I am still getting the failures :)

**Comment by MarianMacik** [comment]
With the latest 0.8.0-SNAPSHOT and 0.12.0-SNAPSHOT, I am not getting these missing classes. Now it filters my packages properly. Good work! Thank you.

**Comment by metlos** [comment]
I've updated the pom.xml in `optaplanner-core` to revapi-maven-plugin 0.8.0-SNAPSHOT and revapi-java-0.12.0-SNAPSHOT (locally built from revapi master) and it seems to be passing:
```
[INFO] --- revapi-maven-plugin:0.8.0-SNAPSHOT:check (check) @ optaplanner-core ---
[INFO] Comparing [org.optaplanner:optaplanner-core:jar:6.4.0.Final] against [org.optaplanner:optaplanner-core:jar:7.0.0-SNAPSHOT] (including their transitive dependencies).
[INFO] API checks completed without failures.
[INFO] 
...
```

**Comment by metlos** [comment]
:)

**Comment by MarianMacik** [comment]
+1
